FROM java:openjdk-8u91-jdk

EXPOSE 8282

ADD bin/wait-for-it.sh /wait-for-it.sh

# FIXME: fix /app volume issue with jdk base image.
RUN mkdir -p /consumer && mkdir -p /producer

ADD gr8-rest-consumer-0.1.jar /consumer/consumer.jar

CMD /bin/sh -c "/wait-for-it.sh redis:6379 --strict && /wait-for-it.sh kafka:9092 --strict && java -jar /consumer/consumer.jar --spring.profiles.active=docker"
