FROM java:openjdk-8u91-jdk

EXPOSE 8080

ADD bin/wait-for-it.sh /wait-for-it.sh

# FIXME: fix /app volume issue with jdk base image.
RUN mkdir -p /stream

ADD gr8-rest-stream-producer-0.1.jar /stream/stream.jar

CMD /bin/sh -c "/wait-for-it.sh redis:6379 --strict && /wait-for-it.sh kafka:9092 --strict && java -jar /stream/stream.jar --spring.profiles.active=docker"
