FROM java:openjdk-8u91-jdk

EXPOSE 8080

ADD bin/wait-for-it.sh /wait-for-it.sh

# FIXME: fix /app volume issue with jdk base image.
RUN mkdir -p /consumer && mkdir -p /producer

ADD gr8-rest-producer-0.1.jar /producer/producer.jar

CMD /bin/sh -c "/wait-for-it.sh redis:6379 --strict && /wait-for-it.sh kafka:9092 --strict && java -jar /producer/producer.jar --spring.profiles.active=docker"
